import { Platform, StyleSheet } from 'react-native'

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: '#f2eadf',
  },
  page: {
    flex: 1,
  },
  pageContent: {
    paddingHorizontal: 16,
    paddingTop: Platform.OS === 'ios' ? 18 : 14,
    paddingBottom: Platform.OS === 'ios' ? 24 : 18,
    gap: 14,
  },
  readyShell: {
    flex: 1,
    paddingHorizontal: 12,
    paddingTop: Platform.OS === 'ios' ? 12 : 10,
    paddingBottom: 8,
    gap: 8,
  },
  readerToolbar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 2,
  },
  readerToolbarImmersive: {
    paddingHorizontal: 0,
    marginBottom: -2,
  },
  hiddenChromeTapRow: {
    alignItems: 'center',
    paddingVertical: 2,
  },
  hiddenChromeTapBtn: {
    borderRadius: 999,
    backgroundColor: '#eadbc8',
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  hiddenChromeTapText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#7d634f',
  },
  toolbarActionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  toolbarBtn: {
    minWidth: 54,
    borderRadius: 999,
    backgroundColor: '#eadbc8',
    paddingHorizontal: 14,
    paddingVertical: 8,
    alignItems: 'center',
  },
  toolbarBtnText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#6f543f',
  },
  toolbarBtnGhost: {
    backgroundColor: '#f1e7d9',
    minWidth: 48,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  toolbarBtnTextGhost: {
    fontSize: 12,
    color: '#8c6d52',
  },
  readerToolbarTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#7d634f',
  },
  immersiveTopCenter: {
    flex: 1,
    alignItems: 'center',
  },
  immersiveTopHint: {
    fontSize: 12,
    fontWeight: '700',
    color: '#9a7a5e',
    letterSpacing: 0.4,
  },
  readyTopCard: {
    paddingHorizontal: 8,
    paddingTop: 4,
    paddingBottom: 2,
    gap: 4,
  },
  immersiveHintRow: {
    alignItems: 'center',
    paddingVertical: 2,
  },
  immersiveHintText: {
    fontSize: 11,
    color: '#9c7d61',
  },
  bookTopLine: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  readerEyebrow: {
    fontSize: 11,
    color: '#9c7d61',
  },
  readerModeDot: {
    width: 4,
    height: 4,
    borderRadius: 999,
    backgroundColor: '#c4a383',
  },
  readyBookName: {
    fontSize: 20,
    lineHeight: 26,
    fontWeight: '700',
    color: '#2b2118',
  },
  readerStatsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 4,
  },
  statPillText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#765a43',
  },
  readerStatsDivider: {
    fontSize: 12,
    color: '#b19377',
    marginHorizontal: 2,
  },
  heroCard: {
    backgroundColor: '#f8f1e5',
    borderRadius: 28,
    borderWidth: 1,
    borderColor: '#ddc8ae',
    paddingHorizontal: 16,
    paddingTop: 18,
    paddingBottom: 14,
    shadowColor: '#8a6440',
    shadowOpacity: 0.08,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
  },
  header: {
    marginBottom: 14,
  },
  title: {
    fontSize: 28,
    fontWeight: '700',
    color: '#2b2117',
  },
  subtitle: {
    marginTop: 4,
    fontSize: 14,
    color: '#806a54',
  },
  apiCard: {
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#e0ceb9',
    backgroundColor: '#fffaf5',
    padding: 12,
  },
  apiLabel: {
    fontSize: 13,
    color: '#7a614a',
    marginBottom: 8,
  },
  apiRow: {
    flexDirection: 'row',
    gap: 8,
    alignItems: 'center',
  },
  apiInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#dbc5ab',
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 11,
    backgroundColor: '#fff',
    fontSize: 16,
    color: '#2d2219',
  },
  apiBtn: {
    borderRadius: 12,
    backgroundColor: '#b36a2e',
    paddingHorizontal: 18,
    paddingVertical: 11,
    justifyContent: 'center',
    alignItems: 'center',
    minWidth: 88,
  },
  apiBtnText: {
    color: '#fff',
    fontWeight: '700',
  },
  importCard: {
    borderRadius: 28,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: '#c99561',
    backgroundColor: '#f7ecde',
    paddingHorizontal: 24,
    paddingVertical: 52,
    alignItems: 'center',
    marginTop: 2,
  },
  importTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#3a291a',
    marginBottom: 10,
  },
  importHint: {
    fontSize: 14,
    lineHeight: 22,
    color: '#81674f',
    textAlign: 'center',
  },
  loadingCard: {
    borderRadius: 24,
    backgroundColor: '#fffaf2',
    borderWidth: 1,
    borderColor: '#e0ceb9',
    paddingVertical: 48,
    alignItems: 'center',
    gap: 14,
  },
  loadingText: {
    fontSize: 14,
    color: '#72563d',
  },
  metaCard: {
    borderRadius: 20,
    backgroundColor: '#fffaf2',
    borderWidth: 1,
    borderColor: '#decbb5',
    padding: 14,
  },
  metaName: {
    fontSize: 14,
    fontWeight: '700',
    color: '#35281d',
    marginBottom: 8,
  },
  metaWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  metaChip: {
    backgroundColor: '#f1dcc4',
    color: '#805637',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
    fontSize: 12,
  },
  metaSwitchBtn: {
    backgroundColor: '#b36a2e',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 5,
  },
  metaSwitchText: {
    color: '#fffaf2',
    fontSize: 12,
    fontWeight: '700',
  },
  libraryCard: {
    borderRadius: 24,
    borderWidth: 1,
    borderColor: '#dcc7b0',
    backgroundColor: '#fffaf2',
    padding: 14,
    gap: 10,
  },
  libraryHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  libraryTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#33261b',
  },
  libraryHint: {
    fontSize: 12,
    color: '#8d7258',
  },
  bookRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: '#ead8c1',
    borderRadius: 16,
    backgroundColor: '#fffdf8',
    paddingHorizontal: 12,
    paddingVertical: 12,
    gap: 10,
  },
  bookActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  bookMeta: {
    flex: 1,
    gap: 4,
  },
  bookName: {
    fontSize: 15,
    fontWeight: '600',
    color: '#2f241b',
  },
  bookSub: {
    fontSize: 12,
    color: '#8a6f55',
  },
  bookAction: {
    fontSize: 13,
    color: '#b36a2e',
    fontWeight: '700',
  },
  bookGhostBtn: {
    borderRadius: 999,
    backgroundColor: '#efe4d4',
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  bookGhostText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#8b6c51',
  },
  bookPrimaryBtn: {
    borderRadius: 999,
    backgroundColor: '#b36a2e',
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  bookPrimaryText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#fffaf2',
  },
  readerCardReady: {
    flex: 1,
    backgroundColor: '#f6efe4',
  },
  readerCardReadyImmersive: {
    marginTop: 0,
  },
  readerContent: {
    paddingHorizontal: 8,
    paddingTop: 8,
    paddingBottom: 36,
  },
  readerContentImmersive: {
    paddingTop: 2,
  },
  sentenceBlock: {
    marginBottom: 6,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  activeSentenceBlock: {
    backgroundColor: '#efe1c9',
  },
  sentence: {
    fontSize: 21,
    lineHeight: 39,
    textAlign: 'left',
    color: '#33271f',
  },
  activeSentence: {
    color: '#6b421f',
    fontWeight: '700',
  },
  controls: {
    borderRadius: 24,
    borderWidth: 1,
    borderColor: '#dcc7b0',
    backgroundColor: '#fffaf3',
    paddingHorizontal: 14,
    paddingTop: 14,
    paddingBottom: 18,
    gap: 10,
    marginTop: 2,
  },
  playerDock: {
    borderRadius: 24,
    borderWidth: 1,
    borderColor: '#d9c5ab',
    backgroundColor: '#fff6ea',
    paddingHorizontal: 14,
    paddingTop: 10,
    paddingBottom: Platform.OS === 'ios' ? 8 : 8,
    gap: 6,
    shadowColor: '#8a6440',
    shadowOpacity: 0.08,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: -2 },
    elevation: 6,
  },
  playerDockImmersive: {
    borderRadius: 18,
    paddingTop: 10,
    paddingBottom: Platform.OS === 'ios' ? 10 : 8,
  },
  drawerHeader: {
    gap: 8,
    paddingBottom: 2,
  },
  drawerQuickRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  drawerQuickSide: {
    width: 62,
    alignItems: 'flex-start',
    justifyContent: 'center',
  },
  drawerQuickSideRight: {
    alignItems: 'flex-end',
  },
  drawerChevron: {
    borderRadius: 999,
    backgroundColor: '#f1e5d4',
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  drawerChevronText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#7b4f28',
  },
  miniPlayBtn: {
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: '#b36a2e',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#8a6440',
    shadowOpacity: 0.14,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 5 },
    elevation: 5,
  },
  miniPauseBtn: {
    backgroundColor: '#d18338',
  },
  drawerSlider: {
    marginTop: 0,
    marginBottom: -2,
  },
  drawerBody: {
    gap: 8,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: '#eadbc8',
  },
  playerTopRow: {
    gap: 2,
  },
  playerNowWrap: {
    width: '100%',
    gap: 1,
  },
  playerNowLabel: {
    fontSize: 11,
    color: '#9a7a5e',
    fontWeight: '700',
  },
  playerSentencePreview: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '600',
    color: '#3a2b20',
  },
  playerMetaInline: {
    fontSize: 10,
    color: '#8a6f55',
  },
  playerMetaInlineImmersive: {
    fontSize: 10,
  },
  playerMiniBadge: {
    borderRadius: 999,
    backgroundColor: '#edd7b8',
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  playerMiniBadgeText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#8a5728',
  },
  settingsCard: {
    borderRadius: 24,
    borderWidth: 1,
    borderColor: '#dcc7b0',
    backgroundColor: '#fffaf2',
    padding: 14,
    gap: 10,
  },
  settingsTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#35281d',
  },
  settingsHint: {
    fontSize: 12,
    lineHeight: 18,
    color: '#8a6f55',
  },
  quotaValue: {
    fontSize: 28,
    fontWeight: '800',
    color: '#b36a2e',
  },
  emptyCard: {
    borderRadius: 24,
    borderWidth: 1,
    borderColor: '#dcc7b0',
    backgroundColor: '#fffaf2',
    paddingHorizontal: 18,
    paddingVertical: 28,
    alignItems: 'center',
    gap: 8,
  },
  emptyTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#35281d',
  },
  emptyHint: {
    fontSize: 13,
    lineHeight: 20,
    color: '#8a6f55',
    textAlign: 'center',
  },
  statusText: {
    fontSize: 11,
    color: '#965523',
    lineHeight: 16,
  },
  buttonRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 4,
  },
  buttonRowImmersive: {
    marginTop: 2,
  },
  ctrlBtn: {
    flex: 1,
    borderRadius: 14,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
  },
  ctrlBtnPrimary: {
    minHeight: 82,
  },
  playBtn: {
    backgroundColor: '#b36a2e',
  },
  pauseBtn: {
    backgroundColor: '#d18338',
  },
  stopBtn: {
    backgroundColor: '#e3d7c9',
  },
  fileBtn: {
    backgroundColor: '#e9dfd2',
  },
  ctrlBtnText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '700',
  },
  ctrlBtnIcon: {
    marginBottom: 2,
  },
  stopBtnText: {
    color: '#5f4b39',
    fontSize: 15,
    fontWeight: '700',
  },
  fileBtnText: {
    color: '#5f4b39',
    fontSize: 15,
    fontWeight: '700',
  },
  settingGrid: {
    gap: 8,
    marginTop: 2,
  },
  inlineToolsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    marginTop: 2,
  },
  inlineToolBtn: {
    borderRadius: 999,
    backgroundColor: '#efe2cf',
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  inlineToolBtnText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#7b4f28',
  },
  inlineToolMeta: {
    flex: 1,
    fontSize: 12,
    color: '#8a6f55',
    textAlign: 'right',
  },
  compactPanel: {
    gap: 8,
    marginTop: 6,
    borderTopWidth: 1,
    borderTopColor: '#eadbc8',
    paddingTop: 10,
  },
  settingCol: {
    gap: 4,
  },
  settingLabel: {
    fontSize: 11,
    color: '#7f6348',
    fontWeight: '600',
  },
  tagWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 4,
  },
  tagBtn: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#d8c2a9',
    backgroundColor: '#fffdf9',
    paddingHorizontal: 10,
    paddingVertical: 6,
    marginRight: 4,
  },
  tagBtnOn: {
    borderColor: '#b36a2e',
    backgroundColor: '#f4dfc5',
  },
  tagText: {
    fontSize: 11,
    color: '#6f5944',
  },
  tagTextOn: {
    color: '#7d4318',
    fontWeight: '700',
  },
  nativeScene: {
    backgroundColor: '#f2eadf',
  },
  nativeTabBar: {
    backgroundColor: '#f6efe4',
    borderTopColor: '#ddccb6',
    borderTopWidth: 1,
    height: Platform.OS === 'ios' ? 60 : 56,
    paddingTop: 4,
    paddingBottom: Platform.OS === 'ios' ? 2 : 4,
    elevation: 12,
    shadowColor: '#8a6440',
    shadowOpacity: 0.04,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: -2 },
  },
  nativeTabBarHidden: {
    display: 'none',
  },
  nativeTabItem: {
    paddingVertical: 2,
  },
  nativeTabIconWrap: {
    marginTop: 0,
    marginBottom: -2,
  },
  nativeTabLabel: {
    fontSize: 11,
    fontWeight: '700',
  },
})
